### ISSUE TITLE
Renewals.

### ISSUE THREAD

**Issue by JonathanRowell** [gbv/paia#41] opened 2015-04-10 13:37 UTC
In the case of renewals of issued items (and similarly the "renewal" of a library card) there is always the issue that the action may involve some fee and the patron may or may not wish to incur this fee at this time. In the case of library cards the classic is the "alle werden älter" case  where the under sixteens suddenly find themselves have to pay a full membership fee. In the case of media there are two areas - a renewal fee which is equal to the issue fee (DVDs, Computer games and the like) and the overdue fee which would have been raised if the media were returned for renewal (because it is overdue). The SIP2 solution to this problem is an "undo", which I don't recommend. It would be better to have a what-if interface, although displaying the information before with the account data helps the reader better than an "oops, if you do this there is a consequence" approach.

Entering a hold is often chargeable, also cancelling a hold can be if an order was placed in a closed stack or staff must run around picking up media. In principle any change of state to the patrons account data ought to have a query interface to decide whether there are consequences for the patron before proceeding.

**Comment by nichtich** [comment] 2015-04-14 13:14
I think this is a duplicate of #31, isn't it?

**Comment by nichtich** [comment] 2015-04-16 13:20
@JonathanRowell how about the solution proposed in https://github.com/gbv/paia/issues/31#issuecomment-93732023?

**Comment by nichtich** [comment] 2015-04-28 07:26
Closing this as duplicate.

**Closed by nichtich** 2015-04-28 07:26 UTC
Labels: PAIA core
