### ISSUE TITLE
More information for fees via PAIA

### ISSUE THREAD

**Issue by olli-gold** [gbv/paia#59] opened 2016-06-15 09:40 UTC
In our opinion PAIA should supply more information about fees, that have been caused by loan transactions (for example fees for late returns). Currently there are no fields specified for that.

We would like to see:
- due date (also if the loan has been renewed after the duedate)
- return date (if the item has been returned)

This information could improve transparency of the fees origin. 

So we suggest adding two fields to the specification:
- fee.duedate
- fee.returndate

Another maybe useful information could be the loandate, but this would be rather optional.

**Comment by nichtich** [comment] 2016-07-04 08:48
The field `document.duedate` is deprected, there is `document.starttime` and `document.endtime` (but connected to a given `document.status`), for this reason I would not use the field name `duedate`.  In general, a fee connected to a specific item could be caused by *any* action:

* requesting
* renewing
* cancelling

and also by any change of a service status

* no service (`0`)
* getting reserved (`1`)
* getting ordered (`2`)
* getting held (aka loan) (`3`)
* getting provided (`4`)
* getting rejected (`5`)

and last but not least by expiration of `endtime` without change of the service status. The whole issue seems more complex than just adding two fields without further explanation when to use these fields.

----

How about adding the following optional field:

* `fee.servicestatus`: service status that caused the fee (one of `0..5`). Not to be confused with the current service status of the item!

There is already

* `fee.date`: date when the fee was claimed

A fee for regular loan or a renewal fee or a fee because expiration of duedate all look the same:

    "item": "...",
    "servicestatus": 3,
    "date": "..."

The client already knows from the `items` request whether the item has been returned or not.

A fee for cancelling order or reservation would have `"servicestatus"=0`.

**Comment by nichtich** [comment] 2016-12-05 10:24
I've added am example of fees at http://gbv.github.io/paia/paia.html#fees The need of additional fields does not convince me. More information could also be included in the field "about". Can I close this issue?

**Comment by olli-gold** [comment] 2016-12-05 14:07
We have discussed that again and now we agree, that the additional fields are not necessary for our use case. Perhaps we will ask to integrate the information into the fee.about field in the VZG PAIA, but as this does not need a specification change, you can close this ticket.

**Closed** 2016-12-05 14:07 UTC

**Comment by nichtich** [comment] 2016-12-05 20:36
Thanks - getting closer to [PAIA 1.4.0](https://github.com/gbv/paia/milestone/5) :smiley:
